
package com.aviolinx.raido.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RaidoAPISoap", targetNamespace = "http://raido.aviolinx.com/api/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RaidoAPISoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ping", action = "http://raido.aviolinx.com/api/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.PingResponse")
    String ping();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "http://raido.aviolinx.com/api/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetVersionResponse")
    String getVersion();

    /**
     * 
     * @param password
     * @param systemUser
     * @param systemUserPassword
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AuthenticateUser", action = "http://raido.aviolinx.com/api/AuthenticateUser")
    @WebResult(name = "AuthenticateUserResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "AuthenticateUser", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.AuthenticateUser")
    @ResponseWrapper(localName = "AuthenticateUserResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.AuthenticateUserResponse")
    boolean authenticateUser(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "SystemUser", targetNamespace = "http://raido.aviolinx.com/api/")
                    String systemUser,
            @WebParam(name = "SystemUserPassword", targetNamespace = "http://raido.aviolinx.com/api/")
                    String systemUserPassword);

    /**
     * 
     * @param password
     * @param scheduleRequestFilter
     * @param scheduleRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfSchedule
     */
    @WebMethod(operationName = "GetSchedules", action = "http://raido.aviolinx.com/api/GetSchedules")
    @WebResult(name = "GetSchedulesResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetSchedules", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetSchedules")
    @ResponseWrapper(localName = "GetSchedulesResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetSchedulesResponse")
    ArrayOfSchedule getSchedules(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "ScheduleRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    ScheduleRequestFilter scheduleRequestFilter,
            @WebParam(name = "ScheduleRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    ScheduleRequestData scheduleRequestData);

    /**
     * 
     * @param flightRequestFilter
     * @param password
     * @param flightRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfFlight
     */
    @WebMethod(operationName = "GetFlights", action = "http://raido.aviolinx.com/api/GetFlights")
    @WebResult(name = "GetFlightsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetFlights", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetFlights")
    @ResponseWrapper(localName = "GetFlightsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetFlightsResponse")
    ArrayOfFlight getFlights(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "FlightRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    FlightRequestFilter flightRequestFilter,
            @WebParam(name = "FlightRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    FlightRequestData flightRequestData);

    /**
     * 
     * @param password
     * @param maintenanceRequestFilter
     * @param username
     * @param maintenanceRequestData
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfMaintenance
     */
    @WebMethod(operationName = "GetMaintenances", action = "http://raido.aviolinx.com/api/GetMaintenances")
    @WebResult(name = "GetMaintenancesResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetMaintenances", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetMaintenances")
    @ResponseWrapper(localName = "GetMaintenancesResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetMaintenancesResponse")
    ArrayOfMaintenance getMaintenances(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "MaintenanceRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    MaintenanceRequestFilter maintenanceRequestFilter,
            @WebParam(name = "MaintenanceRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    MaintenanceRequestData maintenanceRequestData);

    /**
     * 
     * @param password
     * @param crewRequestData
     * @param crewRequestFilter
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfCrew
     */
    @WebMethod(operationName = "GetCrews", action = "http://raido.aviolinx.com/api/GetCrews")
    @WebResult(name = "GetCrewsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetCrews", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetCrews")
    @ResponseWrapper(localName = "GetCrewsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetCrewsResponse")
    ArrayOfCrew getCrews(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "CrewRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    CrewRequestFilter crewRequestFilter,
            @WebParam(name = "CrewRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    CrewRequestData crewRequestData);

    /**
     * 
     * @param password
     * @param userRequestFilter
     * @param userRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfUser
     */
    @WebMethod(operationName = "GetUsers", action = "http://raido.aviolinx.com/api/GetUsers")
    @WebResult(name = "GetUsersResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetUsers", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetUsers")
    @ResponseWrapper(localName = "GetUsersResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetUsersResponse")
    ArrayOfUser getUsers(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "UserRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    UserRequestFilter userRequestFilter,
            @WebParam(name = "UserRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    UserRequestData userRequestData);

    /**
     * 
     * @param password
     * @param rosterRequestFilter
     * @param rosterRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfCrew
     */
    @WebMethod(operationName = "GetRosters", action = "http://raido.aviolinx.com/api/GetRosters")
    @WebResult(name = "GetRostersResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetRosters", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetRosters")
    @ResponseWrapper(localName = "GetRostersResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetRostersResponse")
    ArrayOfCrew getRosters(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "RosterRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    RosterRequestFilter rosterRequestFilter,
            @WebParam(name = "RosterRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    RosterRequestData rosterRequestData);

    /**
     * 
     * @param password
     * @param pairingRequestFilter
     * @param pairingRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfPairing
     */
    @WebMethod(operationName = "GetPairings", action = "http://raido.aviolinx.com/api/GetPairings")
    @WebResult(name = "GetPairingsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetPairings", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetPairings")
    @ResponseWrapper(localName = "GetPairingsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetPairingsResponse")
    ArrayOfPairing getPairings(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "PairingRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    PairingRequestFilter pairingRequestFilter,
            @WebParam(name = "PairingRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    PairingRequestData pairingRequestData);

    /**
     * 
     * @param aircraftRequestData
     * @param password
     * @param username
     * @param aircraftRequestFilter
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfAircraft
     */
    @WebMethod(operationName = "GetAircrafts", action = "http://raido.aviolinx.com/api/GetAircrafts")
    @WebResult(name = "GetAircraftsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetAircrafts", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetAircrafts")
    @ResponseWrapper(localName = "GetAircraftsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetAircraftsResponse")
    ArrayOfAircraft getAircrafts(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "AircraftRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    AircraftRequestFilter aircraftRequestFilter,
            @WebParam(name = "AircraftRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    AircraftRequestData aircraftRequestData);

    /**
     * 
     * @param password
     * @param accumulatedValuesRequestFilter
     * @param accumulatedValuesRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfAccumulatedValue
     */
    @WebMethod(operationName = "GetAccumulatedValues", action = "http://raido.aviolinx.com/api/GetAccumulatedValues")
    @WebResult(name = "GetAccumulatedValuesResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetAccumulatedValues", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetAccumulatedValues")
    @ResponseWrapper(localName = "GetAccumulatedValuesResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetAccumulatedValuesResponse")
    ArrayOfAccumulatedValue getAccumulatedValues(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "AccumulatedValuesRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    AccumulatedValuesRequestFilter accumulatedValuesRequestFilter,
            @WebParam(name = "AccumulatedValuesRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    AccumulatedValuesRequestData accumulatedValuesRequestData);

    /**
     * 
     * @param password
     * @param revisionsRequestFilter
     * @param revisionsRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfCrew
     */
    @WebMethod(operationName = "GetCrewRevisions", action = "http://raido.aviolinx.com/api/GetCrewRevisions")
    @WebResult(name = "GetCrewRevisionsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetCrewRevisions", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetCrewRevisions")
    @ResponseWrapper(localName = "GetCrewRevisionsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetCrewRevisionsResponse")
    ArrayOfCrew getCrewRevisions(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "RevisionsRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    RevisionsRequestFilter revisionsRequestFilter,
            @WebParam(name = "RevisionsRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    RevisionsRequestData revisionsRequestData);

    /**
     * 
     * @param password
     * @param airportRequestFilter
     * @param airportRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfAirport
     */
    @WebMethod(operationName = "GetAirports", action = "http://raido.aviolinx.com/api/GetAirports")
    @WebResult(name = "GetAirportsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetAirports", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetAirports")
    @ResponseWrapper(localName = "GetAirportsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetAirportsResponse")
    ArrayOfAirport getAirports(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "AirportRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    AirportRequestFilter airportRequestFilter,
            @WebParam(name = "AirportRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    AirportRequestData airportRequestData);

    /**
     * 
     * @param crewNumber
     * @param password
     * @param from
     * @param to
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfHotelBooking
     */
    @WebMethod(operationName = "GetHotelBookings", action = "http://raido.aviolinx.com/api/GetHotelBookings")
    @WebResult(name = "GetHotelBookingsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetHotelBookings", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetHotelBookings")
    @ResponseWrapper(localName = "GetHotelBookingsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetHotelBookingsResponse")
    ArrayOfHotelBooking getHotelBookings(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "From", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar from,
            @WebParam(name = "To", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar to,
            @WebParam(name = "CrewNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String crewNumber);

    /**
     * 
     * @param crewNumber
     * @param password
     * @param uniqueId
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetCrewRevision", action = "http://raido.aviolinx.com/api/SetCrewRevision")
    @WebResult(name = "SetCrewRevisionResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetCrewRevision", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetCrewRevision")
    @ResponseWrapper(localName = "SetCrewRevisionResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetCrewRevisionResponse")
    boolean setCrewRevision(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "CrewNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String crewNumber,
            @WebParam(name = "UniqueId", targetNamespace = "http://raido.aviolinx.com/api/")
                    String uniqueId);

    /**
     * 
     * @param configurationDataFilter
     * @param password
     * @param configurationRequestData
     * @param username
     * @return
     *     returns com.aviolinx.raido.api.ConfigurationData
     */
    @WebMethod(operationName = "GetConfigurationData", action = "http://raido.aviolinx.com/api/GetConfigurationData")
    @WebResult(name = "GetConfigurationDataResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetConfigurationData", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetConfigurationData")
    @ResponseWrapper(localName = "GetConfigurationDataResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetConfigurationDataResponse")
    ConfigurationData getConfigurationData(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "ConfigurationRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    ConfigurationRequestData configurationRequestData,
            @WebParam(name = "ConfigurationDataFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    ConfigurationDataFilter configurationDataFilter);

    /**
     * 
     * @param password
     * @param rosterTransactionRequestData
     * @param username
     * @param rosterTransactionRequestFilter
     * @return
     *     returns com.aviolinx.raido.api.ArrayOfCrew
     */
    @WebMethod(operationName = "GetRosterTransactions", action = "http://raido.aviolinx.com/api/GetRosterTransactions")
    @WebResult(name = "GetRosterTransactionsResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "GetRosterTransactions", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetRosterTransactions")
    @ResponseWrapper(localName = "GetRosterTransactionsResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.GetRosterTransactionsResponse")
    ArrayOfCrew getRosterTransactions(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "RosterTransactionRequestFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    RosterTransactionRequestFilter rosterTransactionRequestFilter,
            @WebParam(name = "RosterTransactionRequestData", targetNamespace = "http://raido.aviolinx.com/api/")
                    RosterTransactionRequestData rosterTransactionRequestData);

    /**
     * 
     * @param crewNumber
     * @param password
     * @param rosterDesignator
     * @param flightDate
     * @param departureAirport
     * @param callsign
     * @param arrivalAirport
     * @param username
     * @param flightNumber
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetRosterDesignator", action = "http://raido.aviolinx.com/api/SetRosterDesignator")
    @WebResult(name = "SetRosterDesignatorResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetRosterDesignator", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRosterDesignator")
    @ResponseWrapper(localName = "SetRosterDesignatorResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRosterDesignatorResponse")
    boolean setRosterDesignator(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "FlightNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String flightNumber,
            @WebParam(name = "Callsign", targetNamespace = "http://raido.aviolinx.com/api/")
                    String callsign,
            @WebParam(name = "FlightDate", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar flightDate,
            @WebParam(name = "DepartureAirport", targetNamespace = "http://raido.aviolinx.com/api/")
                    String departureAirport,
            @WebParam(name = "ArrivalAirport", targetNamespace = "http://raido.aviolinx.com/api/")
                    String arrivalAirport,
            @WebParam(name = "CrewNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String crewNumber,
            @WebParam(name = "RosterDesignator", targetNamespace = "http://raido.aviolinx.com/api/")
                    String rosterDesignator);

    /**
     * 
     * @param notes
     * @param flightDate
     * @param departureAirport
     * @param loads
     * @param fuels
     * @param flightNumber
     * @param airports
     * @param password
     * @param times
     * @param delays
     * @param flightplan
     * @param callsign
     * @param voyageReport
     * @param arrivalAirport
     * @param uniqueId
     * @param projectCodes
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetFlightData", action = "http://raido.aviolinx.com/api/SetFlightData")
    @WebResult(name = "SetFlightDataResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetFlightData", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetFlightData")
    @ResponseWrapper(localName = "SetFlightDataResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetFlightDataResponse")
    boolean setFlightData(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "FlightNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String flightNumber,
            @WebParam(name = "Callsign", targetNamespace = "http://raido.aviolinx.com/api/")
                    String callsign,
            @WebParam(name = "FlightDate", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar flightDate,
            @WebParam(name = "UniqueId", targetNamespace = "http://raido.aviolinx.com/api/")
                    Integer uniqueId,
            @WebParam(name = "DepartureAirport", targetNamespace = "http://raido.aviolinx.com/api/")
                    String departureAirport,
            @WebParam(name = "ArrivalAirport", targetNamespace = "http://raido.aviolinx.com/api/")
                    String arrivalAirport,
            @WebParam(name = "Times", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfTime times,
            @WebParam(name = "Delays", targetNamespace = "http://raido.aviolinx.com/api/")
                    Delays delays,
            @WebParam(name = "Loads", targetNamespace = "http://raido.aviolinx.com/api/")
                    Loads loads,
            @WebParam(name = "Notes", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfNote notes,
            @WebParam(name = "Fuels", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfFuel fuels,
            @WebParam(name = "ProjectCodes", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfProjectCode projectCodes,
            @WebParam(name = "VoyageReport", targetNamespace = "http://raido.aviolinx.com/api/")
                    VoyageReport voyageReport,
            @WebParam(name = "Flightplan", targetNamespace = "http://raido.aviolinx.com/api/")
                    Flightplan flightplan,
            @WebParam(name = "Airports", targetNamespace = "http://raido.aviolinx.com/api/")
                    Airports airports);

    /**
     * 
     * @param flightDate
     * @param departureAirport
     * @param deadHeadBookingNumber
     * @param legalExceptions
     * @param flightNumber
     * @param crewNumber
     * @param password
     * @param times
     * @param designators
     * @param callsign
     * @param rosterTime
     * @param arrivalAirport
     * @param uniqueId
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetRosterData", action = "http://raido.aviolinx.com/api/SetRosterData")
    @WebResult(name = "SetRosterDataResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetRosterData", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRosterData")
    @ResponseWrapper(localName = "SetRosterDataResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRosterDataResponse")
    boolean setRosterData(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "FlightNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String flightNumber,
            @WebParam(name = "Callsign", targetNamespace = "http://raido.aviolinx.com/api/")
                    String callsign,
            @WebParam(name = "FlightDate", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar flightDate,
            @WebParam(name = "UniqueId", targetNamespace = "http://raido.aviolinx.com/api/")
                    Integer uniqueId,
            @WebParam(name = "DepartureAirport", targetNamespace = "http://raido.aviolinx.com/api/")
                    String departureAirport,
            @WebParam(name = "ArrivalAirport", targetNamespace = "http://raido.aviolinx.com/api/")
                    String arrivalAirport,
            @WebParam(name = "CrewNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String crewNumber,
            @WebParam(name = "DeadHeadBookingNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String deadHeadBookingNumber,
            @WebParam(name = "Designators", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfRosterDesignator designators,
            @WebParam(name = "RosterTime", targetNamespace = "http://raido.aviolinx.com/api/")
                    RosterTime rosterTime,
            @WebParam(name = "Times", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfTime times,
            @WebParam(name = "LegalExceptions", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfRosterLegalException legalExceptions);

    /**
     * 
     * @param crewNumber
     * @param password
     * @param documents
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetCrewDocument", action = "http://raido.aviolinx.com/api/SetCrewDocument")
    @WebResult(name = "SetCrewDocumentResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetCrewDocument", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetCrewDocument")
    @ResponseWrapper(localName = "SetCrewDocumentResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetCrewDocumentResponse")
    boolean setCrewDocument(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "CrewNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String crewNumber,
            @WebParam(name = "Documents", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfDocument documents);

    /**
     * 
     * @param password
     * @param setRostersFilter
     * @param crews
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetRosters", action = "http://raido.aviolinx.com/api/SetRosters")
    @WebResult(name = "SetRostersResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetRosters", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRosters")
    @ResponseWrapper(localName = "SetRostersResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRostersResponse")
    boolean setRosters(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "SetRostersFilter", targetNamespace = "http://raido.aviolinx.com/api/")
                    SetRostersFilter setRostersFilter,
            @WebParam(name = "Crews", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfCrew crews);

    /**
     * 
     * @param crewNumber
     * @param password
     * @param rosterActivities
     * @param username
     * @param pairings
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetRoster", action = "http://raido.aviolinx.com/api/SetRoster")
    @WebResult(name = "SetRosterResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetRoster", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRoster")
    @ResponseWrapper(localName = "SetRosterResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetRosterResponse")
    boolean setRoster(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "CrewNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String crewNumber,
            @WebParam(name = "RosterActivities", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfRosterActivity rosterActivities,
            @WebParam(name = "Pairings", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfPairing pairings);

    /**
     * 
     * @param lastName
     * @param shortCode1
     * @param addresses
     * @param shortCode2
     * @param gender
     * @param documents
     * @param socialSecurityNumber
     * @param systemUser
     * @param phones
     * @param type
     * @param employeeNumber
     * @param bases
     * @param emails
     * @param password
     * @param contractsData
     * @param qualRankData
     * @param specialRoles
     * @param nickName
     * @param active
     * @param groups
     * @param birthDate
     * @param firstName
     * @param middleName
     * @param seniority
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetCrew", action = "http://raido.aviolinx.com/api/SetCrew")
    @WebResult(name = "SetCrewResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetCrew", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetCrew")
    @ResponseWrapper(localName = "SetCrewResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetCrewResponse")
    boolean setCrew(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "EmployeeNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String employeeNumber,
            @WebParam(name = "FirstName", targetNamespace = "http://raido.aviolinx.com/api/")
                    String firstName,
            @WebParam(name = "MiddleName", targetNamespace = "http://raido.aviolinx.com/api/")
                    String middleName,
            @WebParam(name = "LastName", targetNamespace = "http://raido.aviolinx.com/api/")
                    String lastName,
            @WebParam(name = "NickName", targetNamespace = "http://raido.aviolinx.com/api/")
                    String nickName,
            @WebParam(name = "SocialSecurityNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String socialSecurityNumber,
            @WebParam(name = "ShortCode1", targetNamespace = "http://raido.aviolinx.com/api/")
                    String shortCode1,
            @WebParam(name = "ShortCode2", targetNamespace = "http://raido.aviolinx.com/api/")
                    String shortCode2,
            @WebParam(name = "BirthDate", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar birthDate,
            @WebParam(name = "Gender", targetNamespace = "http://raido.aviolinx.com/api/")
                    String gender,
            @WebParam(name = "Type", targetNamespace = "http://raido.aviolinx.com/api/")
                    String type,
            @WebParam(name = "Active", targetNamespace = "http://raido.aviolinx.com/api/")
                    Boolean active,
            @WebParam(name = "Groups", targetNamespace = "http://raido.aviolinx.com/api/")
                    String groups,
            @WebParam(name = "Seniority", targetNamespace = "http://raido.aviolinx.com/api/")
                    Integer seniority,
            @WebParam(name = "Bases", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfBase bases,
            @WebParam(name = "QualRankData", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfQualRank qualRankData,
            @WebParam(name = "Phones", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfPhone phones,
            @WebParam(name = "Addresses", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfAddress addresses,
            @WebParam(name = "Emails", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfEmail emails,
            @WebParam(name = "Documents", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfDocument documents,
            @WebParam(name = "ContractsData", targetNamespace = "http://raido.aviolinx.com/api/")
                    ContractsData contractsData,
            @WebParam(name = "SpecialRoles", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfSpecialRole specialRoles,
            @WebParam(name = "SystemUser", targetNamespace = "http://raido.aviolinx.com/api/")
                    String systemUser);

    /**
     * 
     * @param lastName
     * @param adUser
     * @param systemUser
     * @param mobile
     * @param active
     * @param groups
     * @param systemUserPassword
     * @param firstName
     * @param password
     * @param typeB
     * @param phone
     * @param voip
     * @param email
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetUser", action = "http://raido.aviolinx.com/api/SetUser")
    @WebResult(name = "SetUserResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetUser", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetUser")
    @ResponseWrapper(localName = "SetUserResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetUserResponse")
    boolean setUser(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "SystemUser", targetNamespace = "http://raido.aviolinx.com/api/")
                    String systemUser,
            @WebParam(name = "SystemUserPassword", targetNamespace = "http://raido.aviolinx.com/api/")
                    String systemUserPassword,
            @WebParam(name = "FirstName", targetNamespace = "http://raido.aviolinx.com/api/")
                    String firstName,
            @WebParam(name = "LastName", targetNamespace = "http://raido.aviolinx.com/api/")
                    String lastName,
            @WebParam(name = "Email", targetNamespace = "http://raido.aviolinx.com/api/")
                    String email,
            @WebParam(name = "TypeB", targetNamespace = "http://raido.aviolinx.com/api/")
                    String typeB,
            @WebParam(name = "Phone", targetNamespace = "http://raido.aviolinx.com/api/")
                    String phone,
            @WebParam(name = "Mobile", targetNamespace = "http://raido.aviolinx.com/api/")
                    String mobile,
            @WebParam(name = "VOIP", targetNamespace = "http://raido.aviolinx.com/api/")
                    String voip,
            @WebParam(name = "ADUser", targetNamespace = "http://raido.aviolinx.com/api/")
                    String adUser,
            @WebParam(name = "Active", targetNamespace = "http://raido.aviolinx.com/api/")
                    Boolean active,
            @WebParam(name = "Groups", targetNamespace = "http://raido.aviolinx.com/api/")
                    String groups);

    /**
     * 
     * @param notes
     * @param type
     * @param aircraftRegistration
     * @param externalReferenceId
     * @param password
     * @param times
     * @param name
     * @param startTime
     * @param endTime
     * @param airportCode
     * @param maintenanceType
     * @param uniqueId
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetMaintenance", action = "http://raido.aviolinx.com/api/SetMaintenance")
    @WebResult(name = "SetMaintenanceResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetMaintenance", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetMaintenance")
    @ResponseWrapper(localName = "SetMaintenanceResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetMaintenanceResponse")
    boolean setMaintenance(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "UniqueId", targetNamespace = "http://raido.aviolinx.com/api/")
                    int uniqueId,
            @WebParam(name = "ExternalReferenceId", targetNamespace = "http://raido.aviolinx.com/api/")
                    Integer externalReferenceId,
            @WebParam(name = "MaintenanceType", targetNamespace = "http://raido.aviolinx.com/api/")
                    MaintenanceType maintenanceType,
            @WebParam(name = "StartTime", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar startTime,
            @WebParam(name = "EndTime", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar endTime,
            @WebParam(name = "Type", targetNamespace = "http://raido.aviolinx.com/api/")
                    String type,
            @WebParam(name = "AirportCode", targetNamespace = "http://raido.aviolinx.com/api/")
                    String airportCode,
            @WebParam(name = "AircraftRegistration", targetNamespace = "http://raido.aviolinx.com/api/")
                    String aircraftRegistration,
            @WebParam(name = "Name", targetNamespace = "http://raido.aviolinx.com/api/")
                    String name,
            @WebParam(name = "Notes", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfNote notes,
            @WebParam(name = "Times", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfTime times);

    /**
     * 
     * @param password
     * @param startTime
     * @param endTime
     * @param airportCode
     * @param maintenanceType
     * @param type
     * @param uniqueId
     * @param username
     * @param aircraftRegistration
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DeleteMaintenance", action = "http://raido.aviolinx.com/api/DeleteMaintenance")
    @WebResult(name = "DeleteMaintenanceResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "DeleteMaintenance", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.DeleteMaintenance")
    @ResponseWrapper(localName = "DeleteMaintenanceResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.DeleteMaintenanceResponse")
    boolean deleteMaintenance(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "UniqueId", targetNamespace = "http://raido.aviolinx.com/api/")
                    int uniqueId,
            @WebParam(name = "MaintenanceType", targetNamespace = "http://raido.aviolinx.com/api/")
                    MaintenanceType maintenanceType,
            @WebParam(name = "StartTime", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar startTime,
            @WebParam(name = "EndTime", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar endTime,
            @WebParam(name = "Type", targetNamespace = "http://raido.aviolinx.com/api/")
                    String type,
            @WebParam(name = "AirportCode", targetNamespace = "http://raido.aviolinx.com/api/")
                    String airportCode,
            @WebParam(name = "AircraftRegistration", targetNamespace = "http://raido.aviolinx.com/api/")
                    String aircraftRegistration);

    /**
     * 
     * @param password
     * @param minimumEquipmentList
     * @param vehicleRegistration
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetAircraftData", action = "http://raido.aviolinx.com/api/SetAircraftData")
    @WebResult(name = "SetAircraftDataResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetAircraftData", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetAircraftData")
    @ResponseWrapper(localName = "SetAircraftDataResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetAircraftDataResponse")
    boolean setAircraftData(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "VehicleRegistration", targetNamespace = "http://raido.aviolinx.com/api/")
                    String vehicleRegistration,
            @WebParam(name = "MinimumEquipmentList", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfMinimumEquipment minimumEquipmentList);

    /**
     * 
     * @param crewNumber
     * @param password
     * @param rosterActivityCode
     * @param filterName
     * @param startTime
     * @param endTime
     * @param uniqueIds
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DeleteRosters", action = "http://raido.aviolinx.com/api/DeleteRosters")
    @WebResult(name = "DeleteRostersResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "DeleteRosters", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.DeleteRosters")
    @ResponseWrapper(localName = "DeleteRostersResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.DeleteRostersResponse")
    boolean deleteRosters(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "UniqueIds", targetNamespace = "http://raido.aviolinx.com/api/")
                    String uniqueIds,
            @WebParam(name = "StartTime", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar startTime,
            @WebParam(name = "EndTime", targetNamespace = "http://raido.aviolinx.com/api/")
                    XMLGregorianCalendar endTime,
            @WebParam(name = "FilterName", targetNamespace = "http://raido.aviolinx.com/api/")
                    String filterName,
            @WebParam(name = "CrewNumber", targetNamespace = "http://raido.aviolinx.com/api/")
                    String crewNumber,
            @WebParam(name = "RosterActivityCode", targetNamespace = "http://raido.aviolinx.com/api/")
                    String rosterActivityCode);

    /**
     * 
     * @param password
     * @param externalCrews
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetExternalCrew", action = "http://raido.aviolinx.com/api/SetExternalCrew")
    @WebResult(name = "SetExternalCrewResult", targetNamespace = "http://raido.aviolinx.com/api/")
    @RequestWrapper(localName = "SetExternalCrew", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetExternalCrew")
    @ResponseWrapper(localName = "SetExternalCrewResponse", targetNamespace = "http://raido.aviolinx.com/api/", className = "com.aviolinx.raido.api.SetExternalCrewResponse")
    boolean setExternalCrew(
            @WebParam(name = "Username", targetNamespace = "http://raido.aviolinx.com/api/")
                    String username,
            @WebParam(name = "Password", targetNamespace = "http://raido.aviolinx.com/api/")
                    String password,
            @WebParam(name = "ExternalCrews", targetNamespace = "http://raido.aviolinx.com/api/")
                    ArrayOfExternalCrew externalCrews);

}
