
package com.aviolinx.raido.api;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RaidoAPI", targetNamespace = "http://raido.aviolinx.com/api/", wsdlLocation = "https://szsnoc.navblue.aero/raidoapi/raidoapi.asmx?WSDL")
public class RaidoAPI
    extends Service
{

    private final static URL RAIDOAPI_WSDL_LOCATION;
    private final static WebServiceException RAIDOAPI_EXCEPTION;
    private final static QName RAIDOAPI_QNAME = new QName("http://raido.aviolinx.com/api/", "RaidoAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://szsnoc.navblue.aero/raidoapi/raidoapi.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RAIDOAPI_WSDL_LOCATION = url;
        RAIDOAPI_EXCEPTION = e;
    }

    public RaidoAPI() {
        super(__getWsdlLocation(), RAIDOAPI_QNAME);
    }

    public RaidoAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), RAIDOAPI_QNAME, features);
    }

    public RaidoAPI(URL wsdlLocation) {
        super(wsdlLocation, RAIDOAPI_QNAME);
    }

    public RaidoAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RAIDOAPI_QNAME, features);
    }

    public RaidoAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RaidoAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RaidoAPISoap
     */
    @WebEndpoint(name = "RaidoAPISoap")
    public RaidoAPISoap getRaidoAPISoap() {
        return super.getPort(new QName("http://raido.aviolinx.com/api/", "RaidoAPISoap"), RaidoAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RaidoAPISoap
     */
    @WebEndpoint(name = "RaidoAPISoap")
    public RaidoAPISoap getRaidoAPISoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://raido.aviolinx.com/api/", "RaidoAPISoap"), RaidoAPISoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RAIDOAPI_EXCEPTION!= null) {
            throw RAIDOAPI_EXCEPTION;
        }
        return RAIDOAPI_WSDL_LOCATION;
    }

}
